"""xains — Natural-language verbalization of ML predictions from pre-computed attributions.

See :mod:`xains.schema`, :mod:`xains.types`, and
:mod:`xains.explainer` for the core public API. See :doc:`docs/design.md`
for the architectural overview.
"""

from xains.config import ExplanationConfig
from xains.explainer import Explainer
from xains.generation import (
    GenerationResult,
    LLMNarrativeGenerator,
    NarrativeGenerator,
    TemplatedNarrativeGenerator,
)
from xains.guardrails import FeatureClaim, GuardrailResult, NarrativeExtraction
from xains.metrics import (
    DisabledProvider,
    ExtractionGrades,
    HuggingFacePerplexityProvider,
    NarrativityGrades,
    OpenAICompatibleEchoProvider,
    PerplexityProvider,
    ccpr,
    cecpr,
    coverage,
    csr,
    dcpr,
    fdr,
    grade_extraction,
    grade_narrativity,
    hallucination_count,
    rank_correlation,
    readability,
    render_grades,
    sign_faithfulness,
    ttcpr,
    value_faithfulness,
    vcpr,
)
from xains.providers import (
    AnthropicProvider,
    LLMProvider,
    LLMResponse,
    MockLLMProvider,
    OpenAICompatibleProvider,
    OpenAIProvider,
    OpenRouterProvider,
)
from xains.schema import (
    DatasetSchema,
    FeatureSchema,
    GraphSpec,
    ImageSpec,
    Modality,
    TargetSchema,
    TextSpec,
)
from xains.types import (
    EdgeContribution,
    ExplanationMode,
    ExplanationRequest,
    ExplanationResult,
    GraphCounterfactual,
    GraphExplanationRequest,
    ImageCounterfactual,
    ImageExplanationRequest,
    NodeContribution,
    Prediction,
    RegionContribution,
    TabularContribution,
    TabularCounterfactual,
    TabularExplanationRequest,
    TextCounterfactual,
    TextExplanationRequest,
    TokenContribution,
)

__version__ = "0.0.1"

__all__ = [
    "AnthropicProvider",
    "DatasetSchema",
    "DisabledProvider",
    "EdgeContribution",
    "Explainer",
    "ExplanationConfig",
    "ExplanationMode",
    "ExplanationRequest",
    "ExplanationResult",
    "ExtractionGrades",
    "FeatureClaim",
    "FeatureSchema",
    "GenerationResult",
    "GraphCounterfactual",
    "GraphExplanationRequest",
    "GraphSpec",
    "GuardrailResult",
    "HuggingFacePerplexityProvider",
    "ImageCounterfactual",
    "ImageExplanationRequest",
    "ImageSpec",
    "LLMNarrativeGenerator",
    "LLMProvider",
    "LLMResponse",
    "MockLLMProvider",
    "Modality",
    "NarrativeExtraction",
    "NarrativeGenerator",
    "NarrativityGrades",
    "NodeContribution",
    "OpenAICompatibleEchoProvider",
    "OpenAICompatibleProvider",
    "OpenAIProvider",
    "OpenRouterProvider",
    "PerplexityProvider",
    "Prediction",
    "RegionContribution",
    "TabularContribution",
    "TabularCounterfactual",
    "TabularExplanationRequest",
    "TargetSchema",
    "TemplatedNarrativeGenerator",
    "TextCounterfactual",
    "TextExplanationRequest",
    "TextSpec",
    "TokenContribution",
    "__version__",
    "ccpr",
    "cecpr",
    "coverage",
    "csr",
    "dcpr",
    "fdr",
    "grade_extraction",
    "grade_narrativity",
    "hallucination_count",
    "rank_correlation",
    "readability",
    "render_grades",
    "sign_faithfulness",
    "ttcpr",
    "value_faithfulness",
    "vcpr",
]
